txtFile=open("/Users/chenchaoyang/Desktop/python/Python/content/content3.txt","w")
txtFile.write("春晓\n")
txtFile.write("唐 孟浩然\n")
txtFile.write("春眠不觉晓,\n")
txtFile.write("处处闻啼鸟。\n")
txtFile.write("夜来风雨声，\n")
txtFile.write("花落知多少。\n")
txtFile.close()